import Head from 'next/head';
import { Inter } from '@next/font/google';
import { TextField } from '@mui/material';
import { useController, useForm } from 'react-hook-form';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const {
    control,
    formState: { errors, isSubmitting, isValid, dirtyFields },
  } = useForm({
    mode: 'onChange',
    criteriaMode: 'all',
    defaultValues: {
      id: '',
    },
  });

  const { field: idField } = useController({
    control,
    name: 'id',
    rules: {
      required: true,
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form>
          <TextField
            {...idField}
            required
            id="outlined-required"
            label="Required"
            defaultValue="Hello World"
          />
        </form>
      </main>
    </>
  );
}
